default_stages: [commit, manual]

repos:
  - repo: local
    hooks:
      - id: check-commit-msg
        name: Check commit message
        entry: scripts/check_commit_msg.sh
        stages: [commit-msg]
        language: system

      - id: fmt-check
        name: Check formatting
        entry: scripts/check_fmt.sh
        stages: [commit]
        language: system

      - id: clippy-check
        name: Run Clippy
        entry: scripts/check_code.sh
        stages: [commit]
        language: system

      - id: python-check-aerugo
        name: Check Aerugo's Python code
        entry: scripts/check_python_code.sh
        stages: [commit]
        language: system

      - id: python-check-calldwell
        name: Check Calldwell's Python code
        entry: bash -c 'cd calldwell && ./scripts/check_code.sh'
        stages: [commit]
        language: system
