targets = [
    { triple = "thumbv7em-none-eabihf" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.9
copyleft = "warn"
unlicensed = "deny"
allow-osi-fsf-free = "neither"
default = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
