[package]
name = "aerugo-cortex-m"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
# homepage.workspace = true
license.workspace = true
description = "Cortex-M specific implementation for Aerugo"

[dependencies]
cortex-m = "0.7.7"
