name: Rust

on:
  push:
    branches:
      - 'main'
      - '**'
  pull_request:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          targets: x86_64-unknown-linux-gnu
      - name: cargo fmt
        run: cargo fmt -- --check --color always

  clippy:
    name: Clippy
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: thumbv7em-none-eabihf
            FEATURES: use-aerugo-cortex-m
          - TARGET: x86_64-unknown-linux-gnu
            FEATURES: use-aerugo-x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.TARGET }}
          components: clippy
      - name: cargo clippy
        run: cargo clippy -p aerugo -F ${{ matrix.FEATURES }} -- -D warnings

  docs:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv7em-none-eabihf
      - name: cargo doc
        run: cargo doc --workspace --no-deps --document-private-items -F use-aerugo-cortex-m

  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: thumbv7em-none-eabihf
            FEATURES: use-aerugo-cortex-m
          - TARGET: x86_64-unknown-linux-gnu
            FEATURES: use-aerugo-x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.TARGET }}
      - name: cargo build
        run: cargo build -p aerugo --features ${{ matrix.FEATURES }}

  examples:
    name: Build examples
    runs-on: ubuntu-latest
    needs: [rustfmt, clippy, docs, build]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv7em-none-eabihf, x86_64-unknown-linux-gnu
      - name: build examples
        run: find examples/ -type f -name Cargo.toml -exec echo "Building {}" \; -execdir cargo build --quiet --release --manifest-path {} +
